excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - AroundEgyptTask/Generated/NeedleGenerated.swift

disabled_rules: # rule identifiers to exclude from running
  - line_length
  - force_cast
  - force_try
  - identifier_name
  - trailing_whitespace
  - type_body_length
  - notification_center_detachment
  - file_length
  - function_body_length
  - function_parameter_count
  - multiple_closures_with_trailing_closure
