# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'AroundEgyptTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AroundEgyptTask
      pod 'Alamofire'
      pod 'Firebase/Crashlytics'
      pod 'SwiftLint'
      pod 'NeedleFoundation'
      pod 'Kingfisher'
      pod 'SwiftUI-Shimmer', :git => 'https://github.com/markiv/SwiftUI-Shimmer.git'
      pod 'AlertToast'

  target 'AroundEgyptTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AroundEgyptTaskUITests' do
    # Pods for testing
  end

end
